### ISSUE TITLE
ModuleNotFoundError: No module named 'astropitography'

### ISSUE THREAD

**Issue by Methyx** [adambaskerville/AstroPitography#8]
Hello !
Thanks for the project ! ... looking forward to use it ! :-)
Sorry, probably a noob question, but when I run : python3 AstroPitography.py on my raspberry pi 4,  I got

Traceback (most recent call last):
  File "/home/phil/astropitography/AstroPitography.py", line 9, in <module>
    import astropitography.utils as utils
ModuleNotFoundError: No module named 'astropitography'

I don't know how to fix that ... 

Thanks in advance :-)

**Comment by bimmui** [comment]
Hello,

The issue you're having may be due to the recent changes in the codebase, so any instructions on using the program prior to the changes aren't that helpful now. A package on PyPI was just recently released. I suggest installing the package using `pip install astropitography`. You can run the program by typing `astropitography`. If any other issues pop up, feel free to reach out!

**Comment by bimmui** [comment]
I see, it's has to do with a mismatch of dependency versions. As of the moment, the program works with a specific version on numpy. I suggest creating a virtual environment and installing astropitography there. I'll have some instructions on how to do that up on the readme in a bit

**Comment by Methyx** [comment]
OK ! Thanks again for quick response !
I'll try that :-)
